### ISSUE TITLE
Wrong volos-cache buffer size

### ISSUE THREAD

**Issue by techana** [apigee-127/volos#100]
Volos-cache stores corrupted data if the cache contents contains utf-8 characters above 0x100. That's because volos counts content characters number not the bytes number.

To solve this, replace line 71 in cache-example/node_modules/volos-cache-common/lib/cache-encoder.js:
`buffer.write(content, pos, content.length, 'utf8');`
with:
`buffer.write(content, pos, Buffer.byteLength(content, 'utf8'), 'utf8');`

**Comment by theganyo** [comment]
Thanks!
