### ISSUE TITLE
Put core modules in seperate git repositories

### ISSUE THREAD

**Issue by fiws** [apigee-127/volos#26]
Hi,

I don't see why all these modules are in a single git repository, but separate on npm.

For example volos-quota-redis has its own npm module but not its own git repo. This is very confusing and makes it more messy to contribute. 
It also seems to cause some bugs that would have been caught instantly if the modules where separate. For example volos-quota-redis is missing underscore in its package.json, which simply makes it unusable without manually installing underscore. (#16)

Please consider splitting into separate git repositories.

**Comment by theganyo** [comment]
I'm closing this issue for now as there are no current plans to break the git repo apart. That said, this may be considered again in the future.
