### ISSUE TITLE
volos-oauth-redis requires client_secret when using the password grant type

### ISSUE THREAD

**Issue by borisirota** [apigee-127/volos#44]
Hi,

As I understand the password credentials flow, the client_secret isn't required because this flow is usually used on mobile or web applications where the credentials can be extracted by a 3rd party\attacker.

As you can see here
https://github.com/apigee-127/volos/blob/master/oauth/redis/lib/redisruntime.js#L126
the clientSecret is required in order to use this flow.
But, when calling the createAndStoreToken function, the first action there is to check the clientSecret only if the grant type is different than 'authorization_code' and 'password', which seems to me like the valid check:
https://github.com/apigee-127/volos/blob/master/oauth/redis/lib/redisruntime.js#L356

It seems to me that the this.mgmt.getAppIdForCredentials check
https://github.com/apigee-127/volos/blob/master/oauth/redis/lib/redisruntime.js#L129
is redundant (and false) and need to be removed because createAndStoreToken already checks the existence of the app correctly based on the grant type.

I hope I'm not missing something :)

Thanks,
Boris

**Comment by borisirota** [comment]
@theganyo In addition to this issue, does the password credentials flow suppose to [return the refreshToken](https://github.com/apigee-127/volos/blob/master/oauth/redis/lib/redisruntime.js#L127) as well ?  
It seems to me that there is no use to the refresh token because it has to know the clientSecret as well and it isn't. As long as security is the subject, its better to expose only the essential data.  
Am I missing something ?

**Comment by theganyo** [comment]
No, password credentials should not return a refresh token.

**Comment by borisirota** [comment]
:+1:

**Comment by theganyo** [comment]
Correction to above: The spec dictates that password credentials flow may optionally return a refresh token.

**Comment by theganyo** [comment]
Hey Boris. Sorry for the delay, but when security is a concern, we need to be careful of course. So upon further investigation and rereading the spec, we are going to have to assume that for this flow the client is a "confidential client" and must authenticate with the client id and secret. If you need to do a username/password flow with a public client (ie. a client that can't secure the client id and secret), you would have to use authorization code or implicit grant.

**Comment by borisirota** [comment]
Ok. Don't forget to return the check for the client secret [here](https://github.com/apigee-127/volos/blob/master/oauth/redis/lib/redisruntime.js#L129) :)

**Comment by theganyo** [comment]
Indeed. Thanks. :)
