### ISSUE TITLE
volos-swagger - add support to verifyToken in remote address

### ISSUE THREAD

**Issue by borisirota** [apigee-127/volos#53]
Hi,

In addition to [#52](https://github.com/apigee-127/volos/issues/52), in a microservices architecture where one server responsible to the oauth2 and all the others are business logic only, there is need to verify the authenticated requests in a remote server. So there is need to tell swagger.yaml the url to verity the token.

I'm not sure how to configure this because the check if to verify in a remote address should be [here](https://github.com/apigee-127/volos/blob/master/swagger/lib/auth-middleware.js#L96) (I think so, not sure) but this lines are in use only when the oauth2 service is defined inside swagger.yaml inside x-a127-service, but, server with business logic only won't contain any of the volos-oauth-*provider*.

It seems like the best place is to add something like "verifyUrl" to the [securitySchemeObject](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#securitySchemeObject) but maybe I'm missing something because I'm not expert in oauth2 authentication flows.

I'll be glad to hear your thoughts :)

Thanks,
Boris

**Comment by theganyo** [comment]
Upon consideration, I think this is outside of Volos scope. It seems to me like it would be more appropriately a general-purpose middleware that would simply access a remote OAuth server (possibly a Volos one :)) to perform the authentication.

**Comment by borisirota** [comment]
ok thanks
