### ISSUE TITLE
volos-swagger - add support for redirection of oauth2 authentication requests to remote server

### ISSUE THREAD

**Issue by borisirota** [apigee-127/volos#54]
Hi,

In addition to [#53](https://github.com/apigee-127/volos/issues/53), in a microservices architecture where one server responsible to the oauth2 and all the others are business logic only, there is need to redirect all authentication requests (authorize, token, invalidate and refresh) to one place.

As I understand there are 2 options for that (I'm really not an expert):
1. Add proxy before the servers which redirects all the authentication requests to the relevant server.
2. Make all the servers accept and understand this requests but redirect them to the relevant server.

To implement option 2 with volos there is need to configure the relevant paths (authorize, token, invalidate and refresh) and let volos to redirect them to the right place.
If I understand correctly, the authorize and token paths can be implemented "out of the box" if volos will support [authorizationUrl & tokenUrl](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#securitySchemeObject). Not sure about other methods (invalidate and refresh).

I'll be glad to hear your thoughts :)

Thanks,
Boris

**Comment by theganyo** [comment]
Like #53, I believe this is out of scope for the Volos module. This sounds something like a passport.js module - but for swagger. It sounds like you have the beginnings of a spec for a neat swagger extension / middleware module. :)

**Comment by borisirota** [comment]
ok thanks :)
