### ISSUE TITLE
volos-oauth-redis related question: How to protect an api from deleted account valid tokens?

### ISSUE THREAD

**Issue by borisirota** [apigee-127/volos#56]
I'm not sure that this is the right place but I'll try anyway :)

The scenario:
1. User asks for a token (password flow).
2. User deactivates\deletes its account.
3. The token is still valid (I know that its possible to invalidate token but there is another scenario where user generates tokens from 2 different clients (browser\mobile) or 2 different browsers -> receives two valid tokens -> impossible to invalidate 2 different token so one is still valid).

How should I protect my API from a valid token that it's owner isn't relevant anymore?

1. I don't see a way where its possible to invalidate all token related to some user (ever if the user's id stored in the token's attributes).
2. Is the only way is to store user's Id inside the token attributes, verify the token, get the user's Id and check that the user is still active for every operation? Its a big overhead for such an end case.
3. In a situation where all user's related data is being deleted as well there is no problem (the api response will be empty), but there are cases where this data isn't being deleted.

Thanks,
Boris

**Comment by theganyo** [comment]
Hey Boris,

If I'm understanding correctly, there are a couple of things that I can think of:

1) Keep the token lifetime small.
2) Save all the tokens in the User account with a timeout and invalidate the ones that are still valid when the User deactivates his or her account.

Scott

**Comment by borisirota** [comment]
@theganyo the second option seems like the best solution to handle this case. Thanks ! :)

**Comment by theganyo** [comment]
You're welcome!
