### ISSUE TITLE
add "updateToken[Scopes]" method to the volos-oauth api

### ISSUE THREAD

**Issue by borisirota** [apigee-127/volos#57]
Hey,

I'm using volos-oauth-redis as my oauth2 provider and using the password flow in order to authenticate users and generate tokens for them on a web app. In addition, I'm using the scope mechanism for authorization.  

I have the following scenario:  
In my application users can change their status (e.g. in ebay, user becomes a seller) and by that be able to make operations that require more permissions than their token allows.  
Now, in the current volos-oauth's api, in order to "adjust" the token to the new status I have to 2 options:  
1. Invalidate the used token, generate a new one with the relevant scopes and return it to the client. In order to do that I have to ask the user for his details and I'm trying to avoid it. It seems to me that in this case, returning new token on a "standard" api call just "pollutes" the api and its not the right solution (I know I can make 2 api calls, one for status change and one for token change, but still, it seems wrong to me that its not atomic and not internal). And this solution won't fix the problem that a user logged in from 2 different devices and asking for status change from one of them.  
2. Same as 1, but generate a new token with the client_credentials flow without the need of user details. Seems a little bit awkward to me that token generated by the password flow has to be replaced by a token generated by a different flow.

It seems to me that the most appropriate solution in this scenario is to be able to update the token's internal details (scopes) without the need of asking for additional details and without the need of invalidating the token.

Does it seems reasonable? Am I missing something? Any security issues with that? :)

Thanks,
Boris

**Comment by theganyo** [comment]
Hey Boris,

Sorry for the delay. I don't think it would be a good idea to modify the tokens after generation. Whether it might open security holes or not, it would at the very least make certain planned implementations in Volos impossible (eg. JSON Web Tokens). What I'd suggest is if you don't want to or can't invalidate and reissue tokens, to maybe just keep this kind of specific authorization information in your database and check it manually.

Best,
Scott

**Comment by borisirota** [comment]
I see. Thanks Scott ! :)
