### ISSUE TITLE
npm run cache 

### ISSUE THREAD

**Issue by dzuluaga** [apigee-127/volos#59]
Hello,

I'm trying to run [volos examples](https://github.com/apigee-127/volos/blob/master/samples/training/README.md#switch-examples-to-apigee-provider) that integrate with Apigee, however ```npm run cache``` throws this error:
```
/samples/training/node_modules/volos-cache-apigee/lib/cache.js:80
  if (!cache) { throw new Error('Apigee cache not available. Specify options.f
                      ^
Error: Apigee cache not available. Specify options.fallback to avoid error.
    at new Cache (/volos/samples/training/node_modules/volos-cache-apigee/lib/cache.js:80:23)
```

What would the fallback option above be? I guess this option would be added to [this object](https://github.com/apigee-127/volos/blob/master/samples/training/cache.js#L9), correct?

Thanks,
Diego

**Comment by theganyo** [comment]
Hi Diego,

Yes, that is correct. And the fallback you would specify would just be another Volos cache object that you've created - an in-memory one.

Scott

**Comment by dzuluaga** [comment]
Thanks Scott. Do you happen to have an example for this? When using local example there was no need to specify the fallback.

**Comment by theganyo** [comment]
Sorry, I misstated what I said a moment ago... I said that you needed to specify a cache that you can created. In fact, you just need to specify a Volos cache provider. It should be as simple as this (though I just wrote and haven't tested the following code):

var apigeeCacheProvider = require('volos-cache-apigee');
var cache = apigeeCacheProvider.create('cache', {
  ttl: 1000,
  fallback: require('volos-cache-memory')
});

The reason you didn't need to specify a fallback when you are running an in-memory version is that the memory cache will always be available. You are now attempting to use an Apigee cache and run your project locally. The Apigee cache, however, is not be available unless you project is deployed on Apigee - thus, the option to have a fallback cache to allow you to still test or run the project on other platforms.

**Comment by dzuluaga** [comment]
Thanks Scott. Code above works like a charm. Is there way to confirm that in fact it's leveraging Apigee Cache without deploying to Edge? Also tried volos-cache-redis.

```
var cache = volos.cache.create('cache', _.extend({
  ttl: 1000, fallback: require('volos-cache-redis')
}, volos.config));
```

**Comment by theganyo** [comment]
Sorry, the only way to use Apigee cache is to deploy on edge. There's no remote version of cache, since it really wouldn't make much sense.

**Comment by dzuluaga** [comment]
Agreed. Thanks!
