### ISSUE TITLE
cache.get callback returns undefined always

### ISSUE THREAD

**Issue by dzuluaga** [apigee-127/volos#60]
hi there,
I'm trying a volos-cache-memory to verify whether a key exists or not (see code below). However, the callback function error parameter always returns undefined, regardless the key exists or not. Am I missing anything?  Thanks!

```javascript
var cm = require('volos-cache-memory');
var cache = cm.create('name', { ttl: 1000 }); // specifies default ttl as 1000 ms
cache.set('key', 'value');
cache.get('key', function(error, cachedValue){
	console.log(cachedValue.toString());
	console.log(error)
});
//cache.set('invalidKey', 'hola value');
cache.get('invalidKey', function(error, cachedValue){
	console.log(error); //returns undefined regardless cache key is defined or not
	//console.log(cachedValue.toString())
});
```

**Comment by theganyo** [comment]
Yes. cache.set() also takes a callback. So you'll need to do the cache.get() inside of that callback in your test - otherwise, the set() will run async and not have run by the time you call get().

**Comment by dzuluaga** [comment]
Thanks Scott. I was also expecting the error from the get callback to indicate whether or not there was a cache hit, which is incorrect. Cache hit can be only be identified by inspecting the value, so when the value is undefined, it means that it wasn't found in cache.
