### ISSUE TITLE
potential security issue with the new API Key functionality

### ISSUE THREAD

**Issue by borisirota** [apigee-127/volos#61]
Hey,

This scenario describes a volos based server:

The API Key expected to be some [client Id](https://github.com/apigee-127/volos/blob/master/oauth/redis/lib/redisruntime.js#L306) ->
Client Id is a public information ->
Can be retrieved from any server that exposes any of the authentication flows (because they require the existence of a client) ->
If in addition this server authenticate some requests with an api key (for example in order to perform operations through the swagger UI interface), an attacker can use any public client Id as API key in order to execute authenticated operations without suppling any personal data and without receiving any explicit API key.

Am I missing something ? :)

**Comment by theganyo** [comment]
Hey Boris,

An API Key and an OAuth token are used for two different things: While an OAuth token is used for identifying a user, an API Key is used to identify an application. Also, the API Key (and, therefore, the client_id for that case) is considered private between an API Provider and an Application Developer.

For what it's worth, I'm guessing you probably wouldn't use OAuth and API Key concurrently - especially on the same app and db.  (Though certainly, if you wished to, nothing is preventing you.)

Does that answer your question?

Scott

**Comment by borisirota** [comment]
I totally misunderstood the api key purpose. Now its clear :) Thanks !
