### ISSUE TITLE
When using volos Analytics, a record should get recorded with "best info available" regardless of status of Quota or OAuth

### ISSUE THREAD

**Issue by DinoChiesa** [apigee-127/volos#64]
Analytics in Volos (running standalone, outside Edge) works like a regular Volos policy step.  If I insert the analytics step before the token validation, then the AX record does not include identity or token status.  If I insert the AX step after the token validation step, then the AX record does include the token status, but only if the token is valid. If the token validation has thrown an exception, then the AX step doesn't run. 

Similarly, suppose I use Volos for OAuth, quota, and analytics.  If I insert the AX tep after oauth and quota, then the AX record gets recorded ONLY if both oauth and quota pass.  If either rejects, then there is no AX record.  Likewise for the cache policy; if the AX step is placed after the volos cache step, and if the request is satisfied from cache,  then we get no AX record. 

This makes it a non-starter for people who want to use nodejs + volos as the basis for an agent model, for managing internal-to-internal API invocations, with the Apigee Edge cloud service.

**Comment by theganyo** [comment]
Thanks! Now how would you say it *should* work?

**Comment by DinoChiesa** [comment]
The way it ought to work is this:
Analytics is "special".  It is not treated as an ordered step, as is the other policy types. Instead it is like a "badge" applied to an API, which causes that API to behave differently, in this way: For an API that includes the analytics "badge", the server will spool an analytics record for *every* request into that API, containing the best and most complete information available about the request, regardless of what other policies are present on the API, and regardless what those other policies did.

Examples:

1. Suppose there is an API proxy with an OAuth token check and the AX badge.  If the OAuth check succeeds, then proxy to the backend.  Upon receipt of the reply from the backend, spool a record containing the developer ID, the app ID, and any other data available from that token, as well as the status and response time from the backend.  If the OAuth token check fails, then return 401/403 to the caller and spool an analytics record containing the information that OAuth failed, and why.  (invalid token, or valid token but mismatch on product, etc)

2. Suppose there is OAuth + quota and the AX badge. For OAuth fail, do as above. For OAuth pass, then if the quota fails, and returns 429 or 400 or whatever, then spool an AX record stating same, but with all available token metadata obtained from the prior successful oauth token validation. If the quota passes, then proxy to the backend, and upon receipt of the response from the backend, spool an AX record containing all the oauth token metadata (as above), the quota used/available, and the status and response time from the backend.

3. If there is OAuth + quota + cache and the AX badge, similarly: if the request is satisfied from cache, then spool an AX record stating as such, but also containing all token and quota metadata.  If the request is not satisfied from cache, then proxy to the backend, fill the cache, and then spool an AX record with the status and response time from the backend, as well as information stating the request was "not filled from cache", plus all the oauth metadata and all the quota metadata. 

In general:
- the AX record is always generated. Semantically Analytics behaves like a "finally" clause in a Java exception block.
- the AX record has "all available information" about the request, regardless how the other policies have resolved

**Comment by theganyo** [comment]
Thanks! I appreciate the explanation and I now understand what you're after in general. 

However, the specific scenarios you've mentioned require more detail - like the precise specification of what this AX record should contain and how these data should be formatted in each of these scenarios (and, I would guess, potentially others). Do you have this or have a link to this specification?

**Comment by DinoChiesa** [comment]
I don't have a specific link to a relevant specification. On the other hand, we can learn the list of fields that other systems commonly log for a transaction.  I'll see if I can track something specific down.
