### ISSUE TITLE
question: How can I get oauth info from within a message handler?

### ISSUE THREAD

**Issue by emcpadden** [apigee-127/volos#65]
I have played with the oauth capabilities in volos (both the redis an apigee oauth handlers) but I can't seem to figure out how to get oauth info when I am in a route handler for a message.

Is there a way to get info like the access token, client id, application, etc.?

Thanks!
...Ed

P.S. Let me know if you'd rather I go somewhere else to ask questions.  I thought asking here might help others who might have the same question.

**Comment by theganyo** [comment]
Hey Ed,

Sorry for the delay. You can access the token - which includes all that info as "request.token" in your handlers. Just let me know if you have any issues or questions.

Scott

**Comment by emcpadden** [comment]
Great!  Thanks Scott, this should work out great.  I'll give it a try tomorrow and let you know if I have any further questions about it.
