### ISSUE TITLE
Invalid value in array api.environments

### ISSUE THREAD

**Issue by joakim-olesen** [apigee-127/volos#67]
a127 version: 0.12.2

Scenario: I execute 'a127 account create accountname' and choose to create a RemoteProxy service targeting an apigee on-premises that does not have any environment called 'prod'.

Part of error message:
Error: {
  "code" : "keymanagement.service.InvalidEnvironment",
  "message" : "Invalid environment prod",
  "contexts" : [ ]
}

Note that I haven't specified anywhere that a127 should use environment 'prod'.

Dirty workaround by hard-coding the environment to use:
In file apigeemgmt.js, replace line 168 with this line:
      environments: [ 'test' ],

**Comment by theganyo** [comment]
Thanks for the report! I've verified this and should have a fix soon.

**Comment by theganyo** [comment]
Good news! This should now be fixed in apigee-127 v. 0.12.3. Please update to the new version and give it a try.

**Comment by joakim-olesen** [comment]
@theganyo, in v. 0.12.3 the issue no longer appears.

Thanks!
