### ISSUE TITLE
An Invalid API Key should create an error with a 403 status and a proper message ...

### ISSUE THREAD

**Issue by emcpadden** [apigee-127/volos#68]
I created a app with a127 that has a method that has security that validates the apiKey.

It all works properly by stopping access if the apikey passed in does not match the apikey for the product.  The problem I'm having is that the error returned is a 500 and the message is blank.

When I debugged into it, it looks like the makeError function in /volos-oauth-common/lib/oauth.js is not handling the case where the apikey is not valid, instead it drops to the default in a switch that checks the code and sets the statusCode to 500.

It would also be helpful if it set the message to something that indicates that the APIKEY is invalid..

What get passed to the makeError function is as follows when the apikey provided is invalid:
code = oauth.v2.InvalidApiKey
message = undefined
errProps = undefined

Please let me know if you need any other information about this.

Thanks,
...Ed

**Comment by theganyo** [comment]
Thanks, Ed!

**Comment by emcpadden** [comment]
I just pulled it down and it works great.  Thanks Scott
