### ISSUE TITLE
Not able to create a fallback cache when configuring a volos-cache-apigee in swagger

### ISSUE THREAD

**Issue by emcpadden** [apigee-127/volos#71]
When running with a RemoteProxy using a127 with a Apigee cache configured in swagger, I was getting errors when it tried to create the fallback cache.  The error I got was that options.fallback did not have a create function.

I just submitted a pull request that seems to fix the problem.  I hope this helps.
pull request: https://github.com/apigee-127/volos/pull/70

I think this might also address an the apigee forum quesiton:
http://community.apigee.com/questions/661/correct-use-of-volos-cache-apigee.html

The questioner was asking about the fallback configuration.

...Ed

**Comment by theganyo** [comment]
Hey Ed. So I just closed this with a patch that allow you to specify the module name (ie. 'volos-cache-memory'). 

Now that I'm thinking about it,though,  I could adjust the swagger fallback option to specify a reference (name) to a cache defined elsewhere in the swagger (similar to specifying the cache to use for an OAuth definition). Do you think this would be more intuitive to users of a127?

**Comment by emcpadden** [comment]
Hmmm ... I actually think that using a reference would be better because it is more similar to what you do for OAuth elsewhere.  Also, it might be nice to reference a different cache for the fallback to maybe make it smaller.

One other question, I assume that the fallback will kick in under a couple of circumstances:
1. if running locally through a RemoteProxy -or-
2. if running on Apigee Edge if the cache name is not configured

Am I correct in this assumption?

Thanks Scott,
...Ed

**Comment by theganyo** [comment]
The truth is with a127 you can already configure the cache to whatever you want based on the deployment environment - the fallback option in 127 is mainly just convenience. But as you might have guessed, I agree that referencing another cache by name would be the most consistent in a127.

As for when it falls back, it only does so when not operating within the Apigee environment.

**Comment by theganyo** [comment]
Done and published. volos/swagger 0.7.5.

**Comment by emcpadden** [comment]
Great!  Thanks Scott.
