### ISSUE TITLE
a127 project deploy: Error: NPM install failed with status code 500

### ISSUE THREAD

**Issue by joakim-olesen** [apigee-127/volos#76]
I'm using a127 v 0.12.3.

Running 'a127 project deploy' often results in error. According to the output, you can find more info in /var/log/apigee/work/npm/npm5574367461897984343.tmp/npm-debug.log

Part of the debug output:

npm http GET https://registry.npmjs.org/volos-analytics-apigee
npm http GET https://registry.npmjs.org/volos-analytics-common
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/volos-analytics-memory
npm http GET https://registry.npmjs.org/volos-cache-apigee
npm http GET https://registry.npmjs.org/volos-cache-memory
npm http GET https://registry.npmjs.org/volos-cache-redis
npm http GET https://registry.npmjs.org/volos-quota-apigee
npm http GET https://registry.npmjs.org/volos-quota-memory
npm http GET https://registry.npmjs.org/volos-quota-redis
npm http GET https://registry.npmjs.org/volos-spikearrest-memory
npm http GET https://registry.npmjs.org/volos-oauth-redis
npm http GET https://registry.npmjs.org/volos-oauth-apigee
npm http GET https://registry.npmjs.org/should
npm http GET https://registry.npmjs.org/supertest
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/volos-cache-apigee
npm http 304 https://registry.npmjs.org/a127-magic
npm http 304 https://registry.npmjs.org/volos-analytics-apigee
npm http 304 https://registry.npmjs.org/volos-analytics-memory
npm http 304 https://registry.npmjs.org/volos-analytics-common
npm http 304 https://registry.npmjs.org/volos-quota-apigee
npm http 304 https://registry.npmjs.org/volos-spikearrest-memory
npm http 304 https://registry.npmjs.org/volos-quota-memory
npm http 304 https://registry.npmjs.org/volos-oauth-redis
npm http 304 https://registry.npmjs.org/should
npm http 304 https://registry.npmjs.org/volos-oauth-apigee
npm http 304 https://registry.npmjs.org/volos-cache-memory
npm http 304 https://registry.npmjs.org/volos-cache-redis
npm http 304 https://registry.npmjs.org/supertest
npm http 304 https://registry.npmjs.org/volos-quota-redis
npm ERR! ENOENT:/var/log/apigee/work/npm/npm5574367461897984343.tmp/node_modules/a127-magic/package.json
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Trireme Trireme
npm ERR! command "./node" "/opt/apigee/apigee-1.0.0.724.8765690.1503240920/lib/node_modules/npm/cli.js" "--registry" "https://registry.npmjs.org" "--cache" "/var/log/apigee/work/npm-cache" "--ignore-scripts" "true" "--bin-links" "false" "install"
npm ERR! cwd /var/log/apigee/work/npm/npm5574367461897984343.tmp
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.3
npm ERR! path /var/log/apigee/work/npm/npm5574367461897984343.tmp/node_modules/a127-magic/package.json
npm ERR! code ENOENT
npm ERR! errno 2
npm http GET https://registry.npmjs.org/on-response
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/volos-spikearrest-common
npm http GET https://registry.npmjs.org/volos-cache-common
npm http GET https://registry.npmjs.org/apigee-access
npm http GET https://registry.npmjs.org/volos-quota-common
npm http GET https://registry.npmjs.org/apigee-access
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/volos-oauth-common
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/basic-auth/1.0.0
npm http GET https://registry.npmjs.org/connect/2.29.1
npm http GET https://registry.npmjs.org/should-equal/0.2.8
npm http GET https://registry.npmjs.org/should-format/0.0.6
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/lru-cache-plus
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/content-disposition/0.5.0
npm http GET https://registry.npmjs.org/volos-management-redis
npm http GET https://registry.npmjs.org/content-type
npm http GET https://registry.npmjs.org/commander/2.6.0
npm http GET https://registry.npmjs.org/cookie/0.1.2
npm http GET https://registry.npmjs.org/cookie-signature/1.0.6
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/depd
npm http GET https://registry.npmjs.org/escape-html/1.0.1
npm http GET https://registry.npmjs.org/etag
npm http GET https://registry.npmjs.org/fresh/0.2.4
npm http GET https://registry.npmjs.org/merge-descriptors/1.0.0
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/mkdirp/0.5.0
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/proxy-addr
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/send/0.12.2
npm http GET https://registry.npmjs.org/utils-merge/1.0.0
npm http GET https://registry.npmjs.org/vary
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/volos-quota-common
npm http 304 https://registry.npmjs.org/volos-cache-common
npm http 304 https://registry.npmjs.org/apigee-access
npm http 304 https://registry.npmjs.org/on-response
npm http 304 https://registry.npmjs.org/apigee-access
npm http 304 https://registry.npmjs.org/redis
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/volos-oauth-common
npm http 304 https://registry.npmjs.org/volos-spikearrest-common
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/basic-auth/1.0.0
npm http 304 https://registry.npmjs.org/connect/2.29.1
npm http 304 https://registry.npmjs.org/should-equal/0.2.8
npm http 304 https://registry.npmjs.org/should-format/0.0.6
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/content-disposition/0.5.0
npm http 304 https://registry.npmjs.org/volos-management-redis
npm http 304 https://registry.npmjs.org/lru-cache-plus
npm http 304 https://registry.npmjs.org/content-type
npm http 304 https://registry.npmjs.org/commander/2.6.0
npm http GET https://registry.npmjs.org/request-summary/1.0.0
npm http GET https://registry.npmjs.org/response-summary/1.0.0
npm http GET https://registry.npmjs.org/should-type/0.0.4
npm http GET https://registry.npmjs.org/qs/1.2.0
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/mime/1.2.11
npm http GET https://registry.npmjs.org/component-emitter/1.1.2
npm http GET https://registry.npmjs.org/methods/1.0.1
npm http GET https://registry.npmjs.org/cookiejar/2.0.1
npm http GET https://registry.npmjs.org/reduce-component/1.0.1
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/form-data/0.1.3
npm http GET https://registry.npmjs.org/readable-stream/1.0.27-1
npm http 304 https://registry.npmjs.org/cookie/0.1.2
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.6
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/depd
npm http 304 https://registry.npmjs.org/escape-html/1.0.1
npm http GET https://registry.npmjs.org/volos-management-common
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/etag
npm http 304 https://registry.npmjs.org/fresh/0.2.4
npm http 304 https://registry.npmjs.org/merge-descriptors/1.0.0
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/mkdirp/0.5.0
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/proxy-addr
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/send/0.12.2
npm http 304 https://registry.npmjs.org/utils-merge/1.0.0
npm http 304 https://registry.npmjs.org/vary
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/request-summary/1.0.0
npm http 304 https://registry.npmjs.org/response-summary/1.0.0
npm http 304 https://registry.npmjs.org/should-type/0.0.4
npm http 304 https://registry.npmjs.org/qs/1.2.0
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm http 304 https://registry.npmjs.org/mime/1.2.11
npm http 304 https://registry.npmjs.org/component-emitter/1.1.2
npm http 304 https://registry.npmjs.org/methods/1.0.1
npm http GET https://registry.npmjs.org/bytes/0.2.1
npm http GET https://registry.npmjs.org/crc/3.2.1
npm http GET https://registry.npmjs.org/forwarded
npm http GET https://registry.npmjs.org/ipaddr.js/0.1.9
npm http GET https://registry.npmjs.org/destroy/1.0.3
npm http GET https://registry.npmjs.org/mime/1.3.4
npm http GET https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/basic-auth-connect/1.0.0
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/bytes/1.0.0
npm http GET https://registry.npmjs.org/on-finished
npm http GET https://registry.npmjs.org/cookie-parser
npm http GET https://registry.npmjs.org/compression
npm http GET https://registry.npmjs.org/connect-timeout
npm http GET https://registry.npmjs.org/csurf
npm http GET https://registry.npmjs.org/errorhandler
npm http GET https://registry.npmjs.org/express-session
npm http GET https://registry.npmjs.org/finalhandler/0.3.4
npm http GET https://registry.npmjs.org/http-errors
npm http 304 https://registry.npmjs.org/cookiejar/2.0.1
npm http 304 https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/form-data/0.1.3
npm http 304 https://registry.npmjs.org/readable-stream/1.0.27-1
npm http GET https://registry.npmjs.org/method-override
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/multiparty/3.3.2
npm http GET https://registry.npmjs.org/on-headers
npm http GET https://registry.npmjs.org/qs/2.4.1
npm http GET https://registry.npmjs.org/response-time
npm http GET https://registry.npmjs.org/serve-favicon
npm http GET https://registry.npmjs.org/serve-index
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/vhost
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/volos-management-common
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/bytes/0.2.1
npm http 304 https://registry.npmjs.org/crc/3.2.1
npm http 304 https://registry.npmjs.org/forwarded
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/ipaddr.js/0.1.9
npm http 304 https://registry.npmjs.org/destroy/1.0.3
npm http 304 https://registry.npmjs.org/mime/1.3.4
npm http 304 https://registry.npmjs.org/ms/0.7.0
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/basic-auth-connect/1.0.0
npm http 304 https://registry.npmjs.org/body-parser
npm http 304 https://registry.npmjs.org/bytes/1.0.0
npm http 304 https://registry.npmjs.org/on-finished
npm http 304 https://registry.npmjs.org/cookie-parser
npm http 304 https://registry.npmjs.org/compression
npm http 304 https://registry.npmjs.org/connect-timeout
npm http 304 https://registry.npmjs.org/csurf
npm http 304 https://registry.npmjs.org/errorhandler
npm http 304 https://registry.npmjs.org/express-session
npm http GET https://registry.npmjs.org/ee-first/1.1.0
npm http 304 https://registry.npmjs.org/finalhandler/0.3.4
npm http 304 https://registry.npmjs.org/http-errors
npm http 304 https://registry.npmjs.org/method-override
npm http 304 https://registry.npmjs.org/morgan
npm http 304 https://registry.npmjs.org/multiparty/3.3.2
npm http 304 https://registry.npmjs.org/on-headers
npm http 304 https://registry.npmjs.org/qs/2.4.1
npm http 304 https://registry.npmjs.org/response-time
npm http 304 https://registry.npmjs.org/serve-favicon
npm http 304 https://registry.npmjs.org/serve-index
npm http 304 https://registry.npmjs.org/serve-static
npm http 304 https://registry.npmjs.org/type-is
npm http 304 https://registry.npmjs.org/vhost
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/statuses
npm http GET https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/media-typer/0.3.0
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/csrf
npm http GET https://registry.npmjs.org/accepts
npm http GET https://registry.npmjs.org/compressible
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/crc/3.2.1
npm http GET https://registry.npmjs.org/uid-safe/1.1.0
npm http GET https://registry.npmjs.org/iconv-lite/0.4.7
npm http GET https://registry.npmjs.org/raw-body/1.3.3
npm http 304 https://registry.npmjs.org/ee-first/1.1.0
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/batch/0.5.2
npm http 304 https://registry.npmjs.org/csrf
npm http 304 https://registry.npmjs.org/accepts
npm http GET https://registry.npmjs.org/base64-url/1.2.1
npm http GET https://registry.npmjs.org/rndm
npm http GET https://registry.npmjs.org/scmp/1.0.0
npm http GET https://registry.npmjs.org/uid-safe
npm http 304 https://registry.npmjs.org/statuses
npm http 304 https://registry.npmjs.org/compressible
npm http 304 https://registry.npmjs.org/media-typer/0.3.0
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/negotiator/0.5.1
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/stream-counter
npm http 304 https://registry.npmjs.org/crc/3.2.1
npm http 304 https://registry.npmjs.org/uid-safe/1.1.0
npm http 304 https://registry.npmjs.org/iconv-lite/0.4.7
npm http GET https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/raw-body/1.3.3
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/batch/0.5.2
npm http 304 https://registry.npmjs.org/base64-url/1.2.1
npm http 304 https://registry.npmjs.org/rndm
npm http GET https://registry.npmjs.org/native-or-bluebird
npm http 304 https://registry.npmjs.org/scmp/1.0.0
npm http 304 https://registry.npmjs.org/uid-safe
npm http 304 https://registry.npmjs.org/negotiator/0.5.1
npm http 304 https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/native-or-bluebird
npm http 304 https://registry.npmjs.org/string_decoder
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/log/apigee/work/npm/npm5574367461897984343.tmp/npm-debug.log
npm ERR! not ok code 0

**Comment by theganyo** [comment]
Closing as duplicate of #77.
