### ISSUE TITLE
a127 project deploy: NPM failed with 504: Gateway Timeout

### ISSUE THREAD

**Issue by joakim-olesen** [apigee-127/volos#77]
I'm using a127 v. 0.12.4. (Note that I have upgraded from v. 0.12.3 since I created the other github issue earlier today).

Running 'a127 project deploy' often results in error messaging.adaptors.http.flow.GatewayTimeout.

Part of the debug output:

Uploading resource .gitignore
Uploading resource app.js
Uploading resource config.zip of size 1047
Uploading resource api.zip of size 2933
Uploading resource deployments.zip of size 591
Uploading resource npm-debug.log
Uploading resource package.json
Uploading resource README.md
Uploading resource test.zip of size 1296
Creating the target endpoint
vhosts = [{"name":"default"}]
proxy = <ProxyEndpoint name="default"><HTTPProxyConnection><BasePath>&#x2F;proxyname</BasePath><VirtualHost>default</VirtualHost></HTTPProxyConnection><RouteRule name="default"><TargetEndpoint>default</TargetEndpoint></RouteRule></ProxyEndpoint>
Creating the proxy endpoint
Running "npm install" at Apigee. This may take several minutes.
NPM failed with 504
{"fault":{"faultstring":"Gateway Timeout","detail":{"errorcode":"messaging.adaptors.http.flow.GatewayTimeout"}}}
  true debug enabled. leaving deployment files: D:\folder\config\.a127_env,D:\folder\config\.a127_secrets +2m
Error: NPM install failed with status code 504
    at Request._callback ...

**Comment by theganyo** [comment]
This can happen occasionally and isn't a Volos problem per se - it's just a timeout on the socket used to perform the deploy command. I suggest that if you run into this issue that you try using the --upload option.

**Comment by joakim-olesen** [comment]
@theganyo, you write '... isn't a Volos problem per se ...'. If we would like this to work without the --upload switch, how can we proceed? Should I create a ticket in some other github repo? Or create a ticket at apigee support?

**Comment by theganyo** [comment]
I've let some folks know, but if you want to track this you might want to open a ticket with Apigee support.
