### ISSUE TITLE
Updating the app.name leaves old keys in redis

### ISSUE THREAD

**Issue by bkonetzny** [apigee-127/volos#86]
Updating the app.name via `RedisManagementSpi.prototype.updateApp()` leaves old keys in redis.

Redis keys after creation of the app with name `OldAppName`:
```
volos:management:my-dev-mail@example.com:OldAppName
```

Redis keys after updating the app.name to `NewAppName`:
```
volos:management:my-dev-mail@example.com:OldAppName
volos:management:my-dev-mail@example.com:NewAppName
```

Calling `RedisManagementSpi.prototype.listDeveloperApps()` to get all apps of one developer will list two apps (`OldAppName` and `NewAppName`) which both point to the same `app.id`.

**Comment by theganyo** [comment]
Thanks for the report! volos-management-redis@0.9.9 should work for you.
