### ISSUE TITLE
Specifying cache options dynamically?

### ISSUE THREAD

**Issue by tanzim** [apigee-127/volos#90]
Hi,
It seems that when using Redis for caching (via `volos-cache-redis`) the only options for configuring the Redis client is via the swagger definition file. While this is great for most situations, sometimes the redis configuration might require additional information like password for the server which needless to say isn't a great fit to be specified in the swagger file itself. Is there a way to supply the client configuration for Redis programmatically?

**Comment by theganyo** [comment]
You can have complete control over creating and using a volos cache programmatically. See this page for information on setting up and using the cache modules: https://github.com/apigee-127/volos/tree/master/cache/common.

**Comment by tanzim** [comment]
Hi,
I think I wasn't elaborate enough earlier, apologies for that.
I'm using Volos using the swagger Volos apply plugin (effectively taking advantage of the fitting mechanism in Swagger node). See https://github.com/apigee-127/volos-swagger-apply/blob/master/README.md

Since the cache configuration is driven via the swagger configuration, I wanted to know if I can modify any of the options dynamically, possibly through the Volos fitting? 
Thanks!

**Comment by theganyo** [comment]
Ah. Ok. So the answer is yes, you can... it's just not especially intuitive at this point (something I need to take a look at later). In any case, probably the most straightforward way right now is something like this:

1. Put the Resource in your Swagger as usual...

```
x-volos-resources:
  MyCache:
    provider: volos-cache-redis
    options:
      host: '127.0.0.1'
      options:
        auth_pass: 'set in app.js'
```

2. Retrieve the swagger object and set the option there before the volos-swagger-apply fitting is created. This should be able to be done in your app.js something like this snippet (although I haven't tested this code):

```
SwaggerExpress.create(init, (err, swaggerExpress) => {
  if (err) throw err

  // set the redis password 
  swaggerExpress.runner.api['x-volos-resources'].MyCache.options.options.auth_pass = 'mypassword'

  swaggerExpress.register(app)
```

**Comment by tanzim** [comment]
@theganyo thanks. It worked like a charm. The only small change I did on top of your suggestion was to move the code that sets the option in a fitting that gets run beforehand, which is equivalent to a middleware that sets swagger options.

**Comment by theganyo** [comment]
Great! That's exactly how I would do it!

**Comment by arne-at-daten-und-bass** [comment]
Hi @theganyo & @tanzim,

could you provide a hint on how to do this with the bagpipes fitting?
 
I am using `volos-oauth-redis` with `swaggerExpress` but (programmatically in my `app.js`) it is not possible to set the `auth_pass` right on time (it is set but not used later on ... which is probably due to the bagpipes flow?).

**My app.js:**
<...>
```
SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  // install middleware

  swaggerExpress.runner.swagger['x-volos-resources'].oauth2.options.options.auth_pass = 'hello world'   // => Successfully set here ... but too late? Because it is not used ... Redis Error: NOAUTH.

  app.use(SwaggerUi(swaggerExpress.runner.swagger));

  // not used for volos oauth ... only for passport (local auth).
  app.use(swaggerExpress.runner.swaggerTools.swaggerSecurity(config.swaggerSecurityHandlers));
 
  swaggerExpress.register(app);

  var port = process.env.PORT || 10010;
  app.listen(port);

  if (swaggerExpress.runner.swagger.paths['/']) {
    console.log('Project started.');
  }
});
```;

**My swagger.yaml:**
<...>
```
x-volos-resources:
  oauth2:
    provider: volos-oauth-redis
    options:
      encryptionKey: 'abc123'
      host: 192.168.103.21
      port: 6379
      db: 3
      options:
        auth_pass: ' '                 // <= trying to set in app.js
      tokenLifetime: 300000
      validGrantTypes:
        - client_credentials
      tokenPaths:
        token: /accesstoken
        invalidate: /invalidate
```

**My config/default.yaml:**
<...>
bagpipes:

```
  volos-swagger-oauth:                             // <= definition
    name: volos-swagger-oauth

  _router:
    name: swagger_router
    mockMode: false
    mockControllersDirs: [ api/mocks ]
    controllersDirs: [ api/controllers/context ]

  _swagger_validate:
    name: swagger_validator
    validateResponse: true

  # pipe for all swagger-node controllers
  swagger_controllers:
    - onError: json_error_handler
    - cors
    - volos-swagger-oauth                         // <= usage
    - swagger_security
    - _swagger_validate
    - express_compatibility
    - _router
```

Thanks for your help!

**Comment by theganyo** [comment]
The intent with the OAuth check is that you provide a function to do it, not a static password. By specifying a function, you'd be able to do as simple or as complex of checks as you need for your scenario.

So in oauth2 definition in your swagger.yaml, you'd add a passwordCheck configuration like this:

    oauth2:
      provider: volos-oauth-redis
      passwordCheck:
        helper: volos
        function: passwordCheck

Then, you'd code the `passwordCheck` function in `api/helpers/volos.js`. See this for an example: https://github.com/apigee-127/swagger-node-examples/tree/master/volos-plugins

Hopefully this helps.

**Comment by arne-at-daten-und-bass** [comment]
Sorry, obviously I didn't make myself clear enough: I was not talking about any oAuth2 related password (I already knew the passwordCheck helper from other volos examples)!

As above in this discussion I meant the **password to the redis db instance** (`auth_pass`)  ... coming from Docker/Docker-Compose (and thus already, centrally defined) in an environment variable.

Sorry for the confusion .. and never mind, I now have everything in place.

Thanks for the quick response anyway.

**Comment by theganyo** [comment]
Sorry about that. Glad you got it sorted out!
