### ISSUE TITLE
volos-oauth-common issue with token's scope array

### ISSUE THREAD

**Issue by jcferrer** [apigee-127/volos#96]
Scott,

I am implementing a volos openam (https://forgerock.org/openam/) connector to create and authenticate OAuth2 tokens. but I ran into an issue when enabling the cache to store the generated tokens.

It seems that the verifyToken @ oauth-cache.js is expecting the scope property to be a string with space-delimited scopes. However openam stores the scope as an array:

i.e.
```
{ access_token: '830b09dc-4504-4be1-b36c-bb584c0dab4f',
  default: '',
  grant_type: 'client_credentials',
  scope: [ 'default' ],
  realm: '/',
  token_type: 'Bearer',
  expires_in: 3145.327 
}
``` 

So it breaks with ``` reply.scope.split is not a function ``` at

```
        var grantedScopes = reply.scope ? reply.scope.split(' ') : [];
```

I am not an expert on OAuth2 so I don't know if this is by design. Do you think the oauth-cache could accommodate support for this a array based scope?

Thanks in advance for your support.

**Comment by theganyo** [comment]
Hey JC,

I assume you're talking about [this line](https://github.com/apigee-127/volos/blob/master/oauth/common/lib/oauth-cache.js#L208)? No, I don't see any reason why we couldn't go ahead and do the Array.isArray(reply.scope) there as well. We're converting to an Array anyway to do the necessary scope checks, this would just allow it to skip the split() call when unneeded. Have you verified that change would solve your issue? Do you want to submit a PR on that?

Thanks,
Scott

**Comment by jcferrer** [comment]
Scott,

That's the line (```volos-oauth-common/lib/oauth-cache.js:208:55```). 

I replaced it with to solve the issue:

```
        var grantedScopes = reply.scope || [];
        if (!Array.isArray(grantedScopes)) {
          grantedScopes = grantedScopes.split(' ');
        }
```

If you want, I can submit a PR (I have never done it before, but I can try) :)

Let me know.

Thanks

**Comment by theganyo** [comment]
No worries. I'll put it in. Thanks!

**Comment by theganyo** [comment]
It's in. Have fun! :)

**Comment by jcferrer** [comment]
Thanks Scott!
