### ISSUE TITLE
Applying SpikeArrest/Quota Policies before Request Validation?

### ISSUE THREAD

**Issue by techana** [apigee-127/volos#98]
It seems that request validation precedes spikearrest and quota policies. It would be more efficient to apply the policies first, then if the call gets a pass, validate the request and continue.

**Comment by theganyo** [comment]
Well, you could integrate Volos into your application however you'd like... That said, while validating the request afterward might be more efficient for certain use cases, it would count invalid requests against the quota which in many cases isn't what one would want.
